version: '2.2'
services:
  todo-db:
    image: postgres
    user: "${UID}:${GID}"
    container_name: todo-db
    environment:
      - POSTGRES_USER=xanderj.system
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo-db
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  todo-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todo-api
    hostname: todo-api.test.xanderj.com
    environment:
      - POSTGRES_URL=todo-db:5432
      - POSTGRES_USER=xanderj.system
      - POSTGRES_PW=password
      - POSTGRES_DB=todo-db
      - FLASK_ENV=development
      - VIRTUAL_HOST=todo-api.test.xanderj.com
      - LETSENCRYPT_HOST=todo-api.test.xanderj.com
      - LETSENCRYPT_EMAIL=xanderj.system@gmail.com
    ports:
      - 5001:5000
    volumes:
      - "./api:/api:ro"

  todo-gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    container_name: todo-gui
    hostname: todo.test.xanderj.com
    environment:
      - VIRTUAL_HOST=todo.test.xanderj.com
      - LETSENCRYPT_HOST=todo.test.xanderj.com
      - LETSENCRYPT_EMAIL=xanderj.system@gmail.com
    ports:
      - 5000:5000

networks:
  default:
    external:
      name: nginx-proxy
