version: '2.2'
services:
  todo-db_test:
    image: postgres
    user: "${UID}:${GID}"
    container_name: todo-db_test
    restart: always
    environment:
      - POSTGRES_USER=xanderj.system
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo-db
    volumes:
      - "./pgdata_test:/var/lib/postgresql/data"

  todo-api_test:
    image: todo-api:test
    container_name: todo-api_test
    restart: always
    hostname: todo-api.test.xanderj.com
    environment:
      - POSTGRES_URL=todo-db_test:5432
      - POSTGRES_USER=xanderj.system
      - POSTGRES_PW=password
      - POSTGRES_DB=todo-db
      - FLASK_ENV=development
      - VIRTUAL_HOST=todo-api.test.xanderj.com
      - LETSENCRYPT_HOST=todo-api.test.xanderj.com
      - LETSENCRYPT_EMAIL=xanderj.system@gmail.com
    volumes:
      - "./api:/api:ro"

  todo-gui_test:
    image: todo-gui:test
    container_name: todo-gui_test
    restart: always
    hostname: todo.test.xanderj.com
    environment:
      - REACT_APP_ENVIRONMENT=test
      - REACT_APP_API_ENDPOINT=https://todo-api.test.xanderj.com
      - VIRTUAL_HOST=todo.test.xanderj.com
      - LETSENCRYPT_HOST=todo.test.xanderj.com
      - LETSENCRYPT_EMAIL=xanderj.system@gmail.com

networks:
  default:
    external:
      name: nginx-proxy
